version: '2'
services:
  greeter:
    image: microhq/greeter-srv
    command:  --registry_address consul
    depends_on:
    - consul
  micro:
    image: microhq/micro
    command: --registry_address consul sidecar
    depends_on:
    - consul
  consul:
    image: consul:v0.6.4
    ports:
    - "8500:8500"
    command: consul agent -dev -client=0.0.0.0
