version: '2'
services:
  bitstampticksubscriber:
    build:
        dockerfile: ./services/BitstampTickSubscriber/Dockerfile
        context: ./
    command: --registry_address consul
    depends_on:
    - consul
  tickrecorder:
    build:
      dockerfile: ./services/TickRecorder/Dockerfile
      context: ./
    command: --registry_address consul
    depends_on:
    - consul
  greeter:
    image: microhq/greeter-srv
    command:  --registry_address consul
    depends_on:
    - consul
  sidecar:
    image: microhq/micro
    command: --registry_address consul --sidecar_cors * sidecar
    ports:
    - "8081:8081"
    depends_on:
    - consul
  consul:
    image: consul:v0.6.4
    ports:
    - "8500:8500"
    command: consul agent -dev -client=0.0.0.0
